//Copyright (C) 2014 - 2015, guardiancrow

#define IDM_EXIT				101
#define IDM_ABOUT				102
#define IDM_RECTMODE			103
#define IDM_CLIENTMODE			104
#define	IDM_WINDOWMODE			105
#define	IDM_FULLSCREENMODE		106
#define IDM_OPENFOLDER			107
#define IDM_OPTION				108
#define IDM_SEPARATOR			120

#define	IDS_APP_TITLE			201
#define	IDC_CLIPSS				202
#define	IDS_IMAGE_BMP			203
#define	IDS_IMAGE_JPEG			204
#define	IDS_IMAGE_PNG			205
#define	IDS_POSTFIX_NONE				211
#define	IDS_POSTFIX_CONSECUTIVENUMBER	212
#define	IDS_POSTFIX_DATETIME			213
#define	IDS_POSTFIX_HASH				214
#define	IDS_RECTMODE			221
#define	IDS_WINDOWMODE			222
#define	IDS_CLIENTMODE			223
#define	IDS_FULLSCREENMODE		224
#define	IDS_MENU_RECTMODE		231
#define	IDS_MENU_WINDOWMODE		232
#define	IDS_MENU_CLIENTMODE		233
#define	IDS_MENU_FULLSCREENMODE	234
#define	IDS_MENU_OPENFOLDER		235
#define	IDS_MENU_OPTION			236
#define	IDS_MENU_EXIT			237

#define IDS_DIALOG_CHOOSESAVEDIR	251

#define IDS_ERR_OK				300
#define	IDS_ERR_INVALIDPARAM	301


#define IDD_OPTIONDIALOG                129
#define IDC_EDITSAVEDIR                 1000
#define IDC_BUTTONSAVEDIR               1001
#define IDC_COMBOSAVEFORMAT             1002
#define IDC_COMBOPOSTFIXMODE            1003
#define IDC_CHECKPULLWINDOW             1004
#define IDC_CHECKICMMODE                1005
#define IDC_CHECKPNGOPTIMIZE            1006
#define IDC_SPINLASTNUMBER              1007
#define IDC_EDITLASTNUMBER              1008
#define IDC_EDITJPEGQUALITY             1009
#define IDC_SPINJPEGQUALITY             1010
#define IDC_STATICFORMAT                1011
#define IDC_STATICCAPTURE               1012
#define IDC_STATICJPEGQUALITY           1013
#define IDC_STATICCONSECUTIVE           1014
#define IDC_STATICPOSTFIX               1015
#define IDC_STATICSAVEDIR               1016
#define IDC_STATIC                      -1
